### ISSUE TITLE
The wrong usage example at README.md

### ISSUE THREAD

**Issue by Wyndace** [vituum/vite-plugin-nunjucks#1]
You have written that usage for *.html files:
```html
<script type="application/json" data-format="liquid">
  {
    "template": "path/to/template.njk",
    "title": "Hello world"
  }
</script>
```
However, in the source code and in fact you should not use `data-format="liquid"` but this `data-format="njk"`

**Comment by lubomirblazekcz** [comment]
Thanks, readme is fixed in 1.0, and usage as <script> was removed
