### ISSUE TITLE
Warning with default config

### ISSUE THREAD

**Issue by alkorlos** [vituum/vite-plugin-nunjucks#4]
Hello!

Based on an example [vituum + nunjucks](https://stackblitz.com/github/vituum/vituum/tree/main/examples/nunjucks)

Here with default config, when run `npm run dev`, warning in CLI
`(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.`

It doesn't seem to affect work, but I'm not sure, in other cases, such a warning was critical. Perhaps the plugin causes such a warning, although everything is working correctly.

**Comment by lubomirblazekcz** [comment]
You can hide it with adding this in config - https://github.com/vituum/vituum/issues/25#issuecomment-1690080284

I might add this as default in next version of vituum
